### ISSUE TITLE
ImportError: No module named 'pycocotools'

### ISSUE THREAD

**Issue by LinkToPast1990** [dBeker/Faster-RCNN-TensorFlow-Python3#1]
D:\software\Anaconda3\python.exe C:/Users/Link/Desktop/tf-faster-rcnn-master/train.py
Traceback (most recent call last):
  File "C:/Users/Link/Desktop/tf-faster-rcnn-master/train.py", line 9, in <module>
    from lib.datasets.factory import get_imdb
  File "C:\Users\Link\Desktop\tf-faster-rcnn-master\lib\datasets\factory.py", line 15, in <module>
    from lib.datasets.coco import coco
  File "C:\Users\Link\Desktop\tf-faster-rcnn-master\lib\datasets\coco.py", line 21, in <module>
    from pycocotools.coco import COCO
ImportError: No module named 'pycocotools'

**Comment by dBeker** [comment]
You need to compile and install pycocotools. I have added an instruction how to do it to readme. Please follow instructions and let me know if I missed something.

**Comment by wyf162** [comment]
my error is same as the above, where the instruction of the pycocotools? thanks

**Comment by morpheusthewhite** [comment]
https://github.com/dBeker/Faster-RCNN-TensorFlow-Python3/blob/master/README.md

**Comment by wyf162** [comment]
> https://github.com/dBeker/Faster-RCNN-TensorFlow-Python3/blob/master/README.md

I need to download pycocotools, and place it in the profiles.
I did not find the infomation of the pycocotools in this readme.md.
please paste the info on this. thank you very much.
or in which step?

**Comment by morpheusthewhite** [comment]
Step 4:
> Go to ./data/coco/PythonAPI
> Run python setup.py build_ext --inplace
> Run python setup.py build_ext install
> Go to ./lib/utils and run python setup.py build_ext --inplace
