### ISSUE TITLE
Error occurred when run python setup.py build_ext --inplace

### ISSUE THREAD

**Issue by supportingvector** [dBeker/Faster-RCNN-TensorFlow-Python3#10]
When run python setup.py build_ext --inplace
running build_ext
building 'pycocotools._mask' extension
error: Unable to find vcvarsall.bat
How can I fix it? I already install vs2010 and >SET VS90COMNTOOLS=%VS100COMNTOOLS% but it still happended

**Comment by dBeker** [comment]
Please check https://blogs.msdn.microsoft.com/pythonengineering/2016/04/11/unable-to-find-vcvarsall-bat/
