### ISSUE TITLE
How to change the number of iterations during training?

### ISSUE THREAD

**Issue by 18342960922** [dBeker/Faster-RCNN-TensorFlow-Python3#102]
I only saw" max_iters" in config.py.what dose it mean?

**Comment by morpheusthewhite** [comment]
Stop spamming issues.

**Comment by 18342960922** [comment]
sorry
I really don't know how to change the number of iterations.
Neural networks have only recently been learned

**Comment by morpheusthewhite** [comment]
It's the number of times the neural net is trained on a batch

**Comment by 18342960922** [comment]
I am sorry to bother you.I know that every time I train a picture, I want to know if the data in the training set has been trained.




------------------ 原始邮件 ------------------
发件人: "morpheusthewhite"<notifications@github.com>; 
发送时间: 2019年9月6日(星期五) 下午4:33
收件人: "dBeker/Faster-RCNN-TensorFlow-Python3"<Faster-RCNN-TensorFlow-Python3@noreply.github.com>; 
抄送: "没时间当网红"<2283934965@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [dBeker/Faster-RCNN-TensorFlow-Python3] How to change the numberof iterations during training? (#102)




It's the number of times the neural net is trained on a batch

**Comment by morpheusthewhite** [comment]
Explain yourself better

**Comment by 18342960922** [comment]
I don't see the epoch parameter.I don't know what epoch is equal to.How many 1000 pictures in the training set can be trained?



------------------ 原始邮件 ------------------
发件人: "morpheusthewhite"<notifications@github.com>; 
发送时间: 2019年9月6日(星期五) 下午5:05
收件人: "dBeker/Faster-RCNN-TensorFlow-Python3"<Faster-RCNN-TensorFlow-Python3@noreply.github.com>; 
抄送: "没时间当网红"<2283934965@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [dBeker/Faster-RCNN-TensorFlow-Python3] How to change the numberof iterations during training? (#102)




Explain yourself better

**Comment by 18342960922** [comment]
batch = ? I  didn't see this parameter.




------------------ 原始邮件 ------------------
发件人: "morpheusthewhite"<notifications@github.com>; 
发送时间: 2019年9月6日(星期五) 下午4:33
收件人: "dBeker/Faster-RCNN-TensorFlow-Python3"<Faster-RCNN-TensorFlow-Python3@noreply.github.com>; 
抄送: "没时间当网红"<2283934965@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [dBeker/Faster-RCNN-TensorFlow-Python3] How to change the numberof iterations during training? (#102)




It's the number of times the neural net is trained on a batch

**Comment by morpheusthewhite** [comment]
Looking at `config.py` in `lib/config/` you can see

```python 
tf.app.flags.DEFINE_integer('batch_size', 256, "Network batch size during training")
tf.app.flags.DEFINE_integer('max_iters', 40000, "Max iteration")  # the number of epochs
```
