### ISSUE TITLE
how use resnet to train fasterrcnn ?

### ISSUE THREAD

**Issue by chenjjjjuu** [dBeker/Faster-RCNN-TensorFlow-Python3#108]
i can run this script by VGG16 on my data now,but how to use renet101 to train and witch document should be modify?

**Comment by morpheusthewhite** [comment]
Duplicate of https://github.com/dBeker/Faster-RCNN-TensorFlow-Python3/issues/79

**Comment by chenjjjjuu** [comment]
DO` you use pascal_voc2007 datasets in this `?

**Comment by morpheusthewhite** [comment]
Yes
