### ISSUE TITLE
Unable to find vcvarsall.bat

### ISSUE THREAD

**Issue by Kervin-L** [dBeker/Faster-RCNN-TensorFlow-Python3#112]
Hello,I run python setup.py build_ext --inplace error.
log:
running build_ext
building 'pycocotools._mask' extension
error: Unable to find vcvarsall.bat

Thank you!

**Comment by wwwpbai** [comment]
@liu978079474 , how did you solve this problem? Thank you!

**Comment by Kervin-L** [comment]
@wwwpbai I downld the Visual Studio 2017, and run it successfully.

**Comment by wwwpbai** [comment]
@liu978079474, I have install the Visual Studio 2017,  and my computer has this file. I tried to reviese msvccompile.py and ran it again, but it failed.

**Comment by Kervin-L** [comment]
@wwwpbai What is the msvccompile.py?I do not find the file.

**Comment by wwwpbai** [comment]
@liu978079474 ,参考这个[链接](Python3.4 用 pip 安装lxml时出现 “Unable to find vcvarsall.bat ”？ - Baichuan Mo的回答 - 知乎
https://www.zhihu.com/question/26857761/answer/333559590)

**Comment by Kervin-L** [comment]
@wwwpbai I can't help you solve the problem, I am very sorry about it.

**Comment by wwwpbai** [comment]
@liu978079474, That's nothing.
