### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.utils.cython_bbox'

### ISSUE THREAD

**Issue by Cliffia123** [dBeker/Faster-RCNN-TensorFlow-Python3#122]
I have done the steps you point, but when I run train.py, my cosole would appear this warnings, how can I solve it ?

**Comment by Nick-cpu-gpu** [comment]
I also have the same problems, which is "ImportError: No module named 'lib.utils.cython_bbox'",i almost had searched all of the blogs,there is no suitable answers.at the first i think  it bacause the python version,so i changed the "python 3.5",but it still didn't work.@Cliffia123

**Comment by liuxinghong1989** [comment]
I used python3.7 version, execute the command python setup.py build_ext --inplace error: command 'cl.exe' failed: No such file or directory all BBS basically can not be resolved, again to seek a solution

**Comment by liuxinghong1989** [comment]
@dBeker

**Comment by liuxinghong1989** [comment]
The solution has been successfully solved by using the compilation tool Visual C++ 2015 x86 x64 Cross Build Tools Command Prompt CD to the directory to be compiled according to the compilation Command provided Cliffia123
