### ISSUE TITLE
something wrong when i try 'python setup.py build_ext --inplace'

### ISSUE THREAD

**Issue by fffupeng** [dBeker/Faster-RCNN-TensorFlow-Python3#13]
building 'pycocotools._mask' extension
error: Unable to find vcvarsall.bat
![default](https://user-images.githubusercontent.com/20182561/35029764-6037902e-fb97-11e7-884e-24f85b2a0982.png)

**Comment by b10112157** [comment]
i have same problem。Have you solved it?

**Comment by dBeker** [comment]
This is not an issue of this branch. Fix your environments!

**Comment by b10112157** [comment]
how to fix environments.
i use win 10 1709
vs2015 
python 3.6.0
anaconda 4.3.0

**Comment by b10112157** [comment]
how to fix environments.
i use win 10 1709
vs2015
python 3.6.0
anaconda 4.3.0

2018-01-20 16:52 GMT+08:00 Deniz Beker <notifications@github.com>:

**Comment by dBeker** [comment]
http://lmgtfy.com/?q=Unable+to+find+vcvarsall.bat

**Comment by b10112157** [comment]
i use it but no solve http://blog.csdn.net/secretx/article/details/17472107


2018-01-20 17:02 GMT+08:00 Deniz Beker <notifications@github.com>:
