### ISSUE TITLE
ValueError: 'pycocotools/_mask.pyx' doesn't match any files

### ISSUE THREAD

**Issue by gimmy4268** [dBeker/Faster-RCNN-TensorFlow-Python3#14]
step 
python setup.py build_ext --inplace

ValueError: 'pycocotools/_mask.pyx' doesn't match any files

**Comment by xqxqwps** [comment]
I had the same problem.

**Comment by xqxqwps** [comment]
Stay ‘building 'pycocotools._mask' extension’ for a long time.

**Comment by rancheng** [comment]
you should go to the directory, to build the mask file. cd to the setup.py folder.

**Comment by rancheng** [comment]
I mean, when you run 
python setup.py build_ext --inplace
You should be inside the directory that setup.py was in.

**Comment by sunnyl95** [comment]
C:\Users\Sunny>F:

F:\>cd F:\python3\Faster-RCNN-TensorFlow-Python3.5-master\data\coco\PythonAPI\

F:\python3\Faster-RCNN-TensorFlow-Python3.5-master\data\coco\PythonAPI>F:\python3\python setup.py build_ext --inplace
running build_ext
building 'pycocotools._mask' extension
cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IF:\python3\lib\site-packages\numpy\core\include -I../common -IF:\python3\include -IF:\python3\include /Tcpycocotools/_mask.c /Fobuild\temp.win-amd64-3.6\Release\pycocotools/_mask.obj
error: command 'cl.exe' failed: No such file or directory

According to what you said, the result of my operation is as above, there are still problems，please guide

**Comment by Tju-AI** [comment]
> 
> 
> C:\Users\Sunny>F:
> 
> F:>cd F:\python3\Faster-RCNN-TensorFlow-Python3.5-master\data\coco\PythonAPI\
> 
> F:\python3\Faster-RCNN-TensorFlow-Python3.5-master\data\coco\PythonAPI>F:\python3\python setup.py build_ext --inplace
> running build_ext
> building 'pycocotools._mask' extension
> cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IF:\python3\lib\site-packages\numpy\core\include -I../common -IF:\python3\include -IF:\python3\include /Tcpycocotools/_mask.c /Fobuild\temp.win-amd64-3.6\Release\pycocotools/_mask.obj
> error: command 'cl.exe' failed: No such file or directory
> 
> According to what you said, the result of my operation is as above, there are still problems，please guide

same question ,have you solved it?

**Comment by smartdevices2ai** [comment]
Please help me to solve these issues:-
After running below command:-
```bash
python model_main.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_thali.config
```

I am getting Error message:-

```log
from object_detection.metrics import coco_tools
  File "C:\ProgramData\Anaconda3\envs\venv_obj_gpu2\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\metrics\coco_tools.py", line 51, in <module>
    from pycocotools import coco
ModuleNotFoundError: No module named 'pycocotools'
```

To solve this I put pycocotools folder in object_detection directory then this error was gone but new error came 
_mask file not found

To solve this I thought of run a command :
I copied PythonAPI in   model/research/     from official cocoapi folder
PWD: model/research
```bash
python PythonAPI/setup.py build_ext install
```
then I got different error:
```log
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64/link.exe    not found.
```
but file is there.

I am using python 3.6 on Windows 10 with Tensorflow gpu 1.12
as per the official doc is provided we need to put pycocotools folder into research directory of Model
but not working.

Please suggest me any way to overcome this.

**Comment by morpheusthewhite** [comment]
> Please help me to solve these issues:-
> After running below command:-
> 
> ```shell
> python model_main.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_thali.config
> ```
> 
> I am getting Error message:-
> 
> ```
> from object_detection.metrics import coco_tools
>   File "C:\ProgramData\Anaconda3\envs\venv_obj_gpu2\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\metrics\coco_tools.py", line 51, in <module>
>     from pycocotools import coco
> ModuleNotFoundError: No module named 'pycocotools'
> ```
> 
> To solve this I put pycocotools folder in object_detection directory then this error was gone but new error came
> _mask file not found
> 
> To solve this I thought of run a command :
> I copied PythonAPI in model/research/ from official cocoapi folder
> PWD: model/research
> 
> ```shell
> python PythonAPI/setup.py build_ext install
> ```

You don't need any additional file. Make sure to follow all steps in the README, above all the 4th.  
  
  
> then I got different error:
> 
> ```
> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64/link.exe    not found.
> ```
> 
> but file is there.
> 

This error is caused by Visual studio, search on the net your error (after trying to follow my previous advice).
