### ISSUE TITLE
ImportError: No module named 'lib.layer_utils.dis_reg'

### ISSUE THREAD

**Issue by AugK** [dBeker/Faster-RCNN-TensorFlow-Python3#15]
Hi,

I have a problem when I ran demo.py. It said "ImportError: No module named 'lib.layer_utils.dis_reg'". And there is no such file in "./lib/layer_utils/".

Would you please help me out? thanks.

**Comment by surajitsaikia27** [comment]
Did you do "make" before running the demo?
