### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by xqxqwps** [dBeker/Faster-RCNN-TensorFlow-Python3#17]
variables_to_restore = self.net.get_variables_to_restore(variables, var_keep_dic)
  File "D:\WorkSpace\Python\Faster-RCNN-TensorFlow-Python3.5\lib\nets\vgg16.py", line 66, in get_variables_to_restore
    if v.name.split(':')[0] in var_keep_dic:
TypeError: argument of type 'NoneType' is not iterable

**Comment by xqxqwps** [comment]
It has been solved
reason: tensorflow version problem,need to add double '\\' to model-file path when save or restore model on windows

**Comment by Renwanlan** [comment]
How to modify it？

**Comment by xqxqwps** [comment]
Function "get_variables_in_checkpoint_file" in train.py
replace file_name with real file path
like this:"var_keep_dic = self.get_variables_in_checkpoint_file('D://Faster-RCNN-TensorFlow-Python3.5\\data\\imagenet_weights\\vgg_16.ckpt')"
