### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.utils.cython_bbox'

### ISSUE THREAD

**Issue by JunsukLee** [dBeker/Faster-RCNN-TensorFlow-Python3#18]
"lib\datasets\imdb.py" line 18, in <module>
    from lib.utils.cython_bbox import bbox_overlaps
ModuleNotFoundError: No module named 'lib.utils.cython_bbox'

help me.

**Comment by Alex-AI-Du** [comment]
May your python version isn't 3.5. Otherwise you can modify ./lib/utils/cython_bbox.cp35-win_amd64.pyd to cython_bbox.pyd and try again.

**Comment by riverbutte** [comment]
@Alex-AI-Du it doesn't work

**Comment by qhdyjs** [comment]
I have the same problem. Have you solved this problem? Thanks

**Comment by SuperLee188** [comment]
@qhdyjs ,I have the same problem. After changing the version to python 35，everything is OK.

**Comment by morpheusthewhite** [comment]
I solved it in https://github.com/morpheusthewhite/Faster-RCNN-TensorFlow-Python3.5 with https://github.com/morpheusthewhite/Faster-RCNN-TensorFlow-Python3.5/commit/67fd5fbd55994aed6f8faabd469c00fc0df7d908

**Comment by morpheusthewhite** [comment]
@dBeker I don't really think you can close this issue since it remains unsolved in your repository

**Comment by morpheusthewhite** [comment]
@dBeker I created a pull request that should solve it (https://github.com/dBeker/Faster-RCNN-TensorFlow-Python3.5/pull/62)

**Comment by creabob** [comment]
i have tried  lots of methods but  it didn't work in py3.6  
please fix it  ,thanks

**Comment by morpheusthewhite** [comment]
> i have tried lots of methods but it didn't work in py3.6
> please fix it ,thanks

Have you downloaded the latest version? To be sure run `git pull` and post here the output

**Comment by creabob** [comment]
i am using this version of faster-rcnn
https://github.com/endernewton/tf-faster-rcnn
and it can be detected under original model in ubuntu and i am trying to train my own datasets
if i succeed i will give some feedback

**Comment by morpheusthewhite** [comment]
Then you should post this error on that issue page, not here

**Comment by creabob** [comment]
sorry ,i means that i used this verson but it can't work in my computer so i changed to https://github.com/endernewton/tf-faster-rcnn this version

**Comment by morpheusthewhite** [comment]
Did you follow all the instructions?

In particular
> Go to `./lib/utils` and run `python setup.py build_ext --inplace`
