### ISSUE TITLE
How to create module 'lib.utils.cython_bbox'?

### ISSUE THREAD

**Issue by Alex-AI-Du** [dBeker/Faster-RCNN-TensorFlow-Python3#19]
Hi DBeker,

I use Win10+TF+python_3.6. I see the error "ModuleNotFoundError: No module named 'lib.utils.cython_bbox'". So I think author should know how to create lib.utils.cython_bbox for python_3.6. Could you tell me your way?

Thanks
Aeon

**Comment by qhdyjs** [comment]
I have the same problem.I also use Win10+TF+python_3.6.  Have you solved this problem? Thank you very much

**Comment by QQ2737499951** [comment]
我win10+python3.66+vs2017+cuda9.2下运行tensorflow版的faster-Rcnn
 

配置Faster-RCNN（网上找的的都是基于python3.5的，不支持py3.6，本文主要尝试用py3.6配置）
https://blog.csdn.net/qq_41895190/article/details/82877883

**Comment by dBeker** [comment]
Compile the bbox by following the instructions.

**Comment by aiFTong** [comment]
> thank dalao~

**Comment by sdzbft** [comment]
> 的都是基于python3.5的，不支持py3.6，本文主要尝试用

thank dalao~
