### ISSUE TITLE
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

### ISSUE THREAD

**Issue by LinkToPast1990** [dBeker/Faster-RCNN-TensorFlow-Python3#2]
PS C:\Users\Link> cd C:\Users\Link\Desktop\coco-master\PythonAPI
PS C:\Users\Link\Desktop\coco-master\PythonAPI> python setup.py install
Compiling pycocotools/_mask.pyx because it changed.
[1/1] Cythonizing pycocotools/_mask.pyx
running install
running build
running build_py
creating build
creating build\lib.win-amd64-3.5
creating build\lib.win-amd64-3.5\pycocotools
copying pycocotools\coco.py -> build\lib.win-amd64-3.5\pycocotools
copying pycocotools\cocoeval.py -> build\lib.win-amd64-3.5\pycocotools
copying pycocotools\mask.py -> build\lib.win-amd64-3.5\pycocotools
copying pycocotools\__init__.py -> build\lib.win-amd64-3.5\pycocotools
running build_ext
building 'pycocotools._mask' extension
creating build\temp.win-amd64-3.5
creating build\temp.win-amd64-3.5\Release
creating build\temp.win-amd64-3.5\Release\pycocotools
creating build\temp.win-amd64-3.5\common
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -ID:\software\Anaconda3\lib\site-packages\numpy\core\include -I../common -ID:\software\Anaconda3\include -ID:\software\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcpycocotools/_mask.c /Fobuild\temp.win-amd64-3.5\Release\pycocotools/_mask.obj -Wno-cpp -Wno-unused-function -std=c99
cl : Command line error D8021 : invalid numeric argument '/Wno-cpp'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

**Comment by dBeker** [comment]
I have pushed modified version of Py Coco Tools. Please pull branch and follow the instructions at readme files. If you find another issue, please let me know.
