### ISSUE TITLE
demo.py

### ISSUE THREAD

**Issue by jingdanyang6967634** [dBeker/Faster-RCNN-TensorFlow-Python3#20]
142 line
net.create_architecture(sess, "TEST", 21,tag='default', anchor_scales=[8, 16, 32])

  File "E:\study_software\pycharm\install\PyCharm Community Edition 2018.1\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "E:\study_software\pycharm\install\PyCharm Community Edition 2018.1\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "E:\study_software\pycharm\install\PyCharm Community Edition 2018.1\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "E:\study_software\pycharm\install\PyCharm Community Edition 2018.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "F:/project/Faster-RCNN-TensorFlow-Python3.5-master/demo.py", line 144, in <module>
    tag='default', anchor_scales=[8, 16, 32])
  File "F:\project\Faster-RCNN-TensorFlow-Python3.5-master\lib\nets\network.py", line 283, in create_architecture
    weights_regularizer = tf.contrib.layers.l2_regularizer(cfg.FLAGS.weight_decay)
  File "E:\study_software\anaconda\anzhuang\envs\tensorflow\lib\site-packages\tensorflow\python\platform\flags.py", line 84, in __getattr__
    wrapped(_sys.argv)
  File "E:\study_software\anaconda\anzhuang\envs\tensorflow\lib\site-packages\absl\flags\_flagvalues.py", line 630, in __call__
    name, value, suggestions=suggestions)
`absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'net'. Did you mean: network ?`

**Comment by xupinjie** [comment]
just change `tf.app.flags.DEFINE_string('network', "vgg16", "The network to be used as backbone")` to `tf.app.flags.DEFINE_string('net', "vgg16", "The network to be used as backbone")` in file `\lib\config\config.py`

**Comment by gmt710** [comment]
@Jasonxu033    yes,it works.Thanks so much.

**Comment by gmt710** [comment]
@Jasonxu033  I am curious about how you find the solution.

**Comment by dBeker** [comment]
@Jasonxu033 Can you send the PR for those changes?

**Comment by renlicheng** [comment]
@Jasonxu033  老哥你怎么发现的这个问题

**Comment by jingdanyang6967634** [comment]
什么问题？




------------------ 原始邮件 ------------------
发件人: "LiCheng Ren"<notifications@github.com>; 
发送时间: 2019年4月21日(星期天) 晚上7:14
收件人: "dBeker/Faster-RCNN-TensorFlow-Python3.5"<Faster-RCNN-TensorFlow-Python3.5@noreply.github.com>; 
抄送: "敬丹阳"<497205974@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [dBeker/Faster-RCNN-TensorFlow-Python3.5] demo.py (#20)




@Jasonxu033  老哥你怎么发现的这个问题

**Comment by renlicheng** [comment]
> 什么问题？
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "LiCheng Ren"<notifications@github.com>; 发送时间: 2019年4月21日(星期天) 晚上7:14 收件人: "dBeker/Faster-RCNN-TensorFlow-Python3.5"<Faster-RCNN-TensorFlow-Python3.5@noreply.github.com>; 抄送: "敬丹阳"<497205974@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [dBeker/Faster-RCNN-TensorFlow-Python3.5] demo.py (#20) @Jasonxu033 老哥你怎么发现的这个问题 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

https://github.com/dBeker/Faster-RCNN-TensorFlow-Python3.5/issues/20#issuecomment-389060700
原答案：just change tf.app.flags.DEFINE_string('network', "vgg16", "The network to be used as backbone") to tf.app.flags.DEFINE_string('net', "vgg16", "The network to be used as backbone") in file \lib\config\config.py

**Comment by jingdanyang6967634** [comment]
> > 什么问题？
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "LiCheng Ren"[notifications@github.com](mailto:notifications@github.com); 发送时间: 2019年4月21日(星期天) 晚上7:14 收件人: "dBeker/Faster-RCNN-TensorFlow-Python3.5"[Faster-RCNN-TensorFlow-Python3.5@noreply.github.com](mailto:Faster-RCNN-TensorFlow-Python3.5@noreply.github.com); 抄送: "敬丹阳"[497205974@qq.com](mailto:497205974@qq.com); "Author"[author@noreply.github.com](mailto:author@noreply.github.com); 主题: Re: [dBeker/Faster-RCNN-TensorFlow-Python3.5] demo.py (#20) @Jasonxu033 老哥你怎么发现的这个问题 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> [#20 (comment)](https://github.com/dBeker/Faster-RCNN-TensorFlow-Python3.5/issues/20#issuecomment-389060700)
> 原答案：just change tf.app.flags.DEFINE_string('network', "vgg16", "The network to be used as backbone") to tf.app.flags.DEFINE_string('net', "vgg16", "The network to be used as backbone") in file \lib\config\config.py

我只是提问者，我也不知道他怎么发现的
