### ISSUE TITLE
How to test model?

### ISSUE THREAD

**Issue by riverbutte** [dBeker/Faster-RCNN-TensorFlow-Python3#22]
There is  no test.py, can you provide it ?

**Comment by sunnyl95** [comment]
demo.py is the test.py

**Comment by changsyuyang** [comment]
i have question  how to eval my test data?

**Comment by gmt710** [comment]
@sunnyl95 I run the demo.py,get an error like that "absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'net'. Did you mean: network ?"

**Comment by gmt710** [comment]
@sunnyl95    ok,I see somebody in page two have solved this problem by this.
just change tf.app.flags.DEFINE_string('network', "vgg16", "The network to be used as backbone") to tf.app.flags.DEFINE_string('net', "vgg16", "The network to be used as backbone") in file \lib\config\config.py
