### ISSUE TITLE
how to  eval the accuracy

### ISSUE THREAD

**Issue by changsyuyang** [dBeker/Faster-RCNN-TensorFlow-Python3#23]
when i finish train my own  data  , how can i know my  mAP? can anyone answer me?  thanks a lot

**Comment by niuniu111** [comment]
I have the same question,do the question fixed?If you have fixed,can you guide me?

**Comment by XN-0808** [comment]
@changsyuyang @niuniu111 I meet the same question,have you solved it yet? I would appreciate it  if you can answer me!
