### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by MulinYu** [dBeker/Faster-RCNN-TensorFlow-Python3#24]
Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./data/imagenet_weights/vgg16.ckpt

Is there a problem with my data file?

**Comment by MulinYu** [comment]
ok， i have fixed, be careful of the name of vgg16.ckpt instead of vgg_16.ckpt.

**Comment by morpheusthewhite** [comment]
You should close this issue
