### ISSUE TITLE
I met a strange qustion,and don't know how to fix it,I hope to get your help,Thanks

### ISSUE THREAD

**Issue by niuniu111** [dBeker/Faster-RCNN-TensorFlow-Python3#29]
d:\faster-rcnn-tensorflow-python3.5-master\lib\layer_utils\proposal_target_layer.py(139)_sample_rois()
-> keep_inds = np.append(fg_inds, bg_inds)
(Pdb) 
Process finished with exit code 1

**Comment by cooko107** [comment]
i met the same question with u  and i found that the loss_box always be nan lisk this:
iter: 2 / 40000, total loss: nan
 >>> rpn_loss_cls: 0.716178
 >>> rpn_loss_box: nan
 >>> loss_cls: 3.397649
 >>> loss_box: nan

plz tell me if u solve the problem .

**Comment by lccate** [comment]
I also met the question, because the picture is too big, originally, the size of my picture is about 980*1000, i resized it as 512*512, it's ok

**Comment by XN-0808** [comment]
> I also met the question, because the picture is too big, originally, the size of my picture is about 980_1000, i resized it as 512_512, it's ok

This problem may be related to the size of the image, but my image size is normal, but the same problem occurs

**Comment by lccate** [comment]
> > I also met the question, because the picture is too big, originally, the size of my picture is about 980_1000, i resized it as 512_512, it's ok
> 
> This problem may be related to the size of the image, but my image size is normal, but the same problem occurs

是用的自己的数据集吗，可能是标注的问题，标注的时候注意不要紧贴图片边缘

**Comment by XN-0808** [comment]
> > > I also met the question, because the picture is too big, originally, the size of my picture is about 980_1000, i resized it as 512_512, it's ok
> > 
> > 
> > This problem may be related to the size of the image, but my image size is normal, but the same problem occurs
> 
> 是用的自己的数据集吗，可能是标注的问题，标注的时候注意不要紧贴图片边缘

我有点抓狂了，我一共跑了三个数据集，开始的是PascalVOC2007，没问题，第二个数据集出现了pdb问题，确实如你所说的Bbox紧贴边缘，没时间重新标注图片，还好在修改pascal_voc.py和imdb.py代码之后，运行成功。但是在跑第三个数据集的时候又出现了pdb问题，我自认为紧贴边缘的问题已经解决了，现在这个问题又出现了，请问你知道还有可能的原因吗？或者你还在其他数据集上试过吗？
第二个问题就是，这份代码不能计算mAp，你知道怎么修改吗？

**Comment by niuniu111** [comment]
我遇到的问题和你的一样，目前尚未解决，在寻找方法中


------------------ 原始邮件 ------------------
发件人: "XN-0808"<notifications@github.com>;
发送时间: 2018年12月10日(星期一) 下午4:19
收件人: "dBeker/Faster-RCNN-TensorFlow-Python3.5"<Faster-RCNN-TensorFlow-Python3.5@noreply.github.com>;
抄送: "唯y1╮拥有"<1214158021@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [dBeker/Faster-RCNN-TensorFlow-Python3.5] I met a strangequstion,and don't know how to fix it,I hope to get your help,Thanks (#29)



   
I also met the question, because the picture is too big, originally, the size of my picture is about 980_1000, i resized it as 512_512, it's ok
  
This problem may be related to the size of the image, but my image size is normal, but the same problem occurs
  
是用的自己的数据集吗，可能是标注的问题，标注的时候注意不要紧贴图片边缘
  
我有点抓狂了，我一共跑了三个数据集，开始的是PascalVOC2007，没问题，第二个数据集出现了pdb问题，确实如你所说的Bbox紧贴边缘，没时间重新标注图片，还好在修改pascal_voc.py和imdb.py代码之后，运行成功。但是在跑第三个数据集的时候又出现了pdb问题，我自认为紧贴边缘的问题已经解决了，现在这个问题又出现了，请问你知道还有可能的原因吗？或者你还在其他数据集上试过吗？
 第二个问题就是，这份代码不能计算mAp，你知道怎么修改吗？

**Comment by lccate** [comment]
> > > > I also met the question, because the picture is too big, originally, the size of my picture is about 980_1000, i resized it as 512_512, it's ok
> > > 
> > > 
> > > This problem may be related to the size of the image, but my image size is normal, but the same problem occurs
> > 
> > 
> > 是用的自己的数据集吗，可能是标注的问题，标注的时候注意不要紧贴图片边缘
> 
> 我有点抓狂了，我一共跑了三个数据集，开始的是PascalVOC2007，没问题，第二个数据集出现了pdb问题，确实如你所说的Bbox紧贴边缘，没时间重新标注图片，还好在修改pascal_voc.py和imdb.py代码之后，运行成功。但是在跑第三个数据集的时候又出现了pdb问题，我自认为紧贴边缘的问题已经解决了，现在这个问题又出现了，请问你知道还有可能的原因吗？或者你还在其他数据集上试过吗？
> 第二个问题就是，这份代码不能计算mAp，你知道怎么修改吗？

是训练一开始就出现pdb的问题还是训练了几次iteration后才出现这个问题

**Comment by niuniu111** [comment]
我是训练一会儿再出现的，我跑的是cityperson数据集，你跑的是这个数据吗




------------------ 原始邮件 ------------------
发件人: "ccate"<notifications@github.com>;
发送时间: 2018年12月10日(星期一) 下午5:26
收件人: "dBeker/Faster-RCNN-TensorFlow-Python3.5"<Faster-RCNN-TensorFlow-Python3.5@noreply.github.com>;
抄送: "唯y1╮拥有"<1214158021@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [dBeker/Faster-RCNN-TensorFlow-Python3.5] I met a strangequstion,and don't know how to fix it,I hope to get your help,Thanks (#29)



    
I also met the question, because the picture is too big, originally, the size of my picture is about 980_1000, i resized it as 512_512, it's ok
  
This problem may be related to the size of the image, but my image size is normal, but the same problem occurs
  
是用的自己的数据集吗，可能是标注的问题，标注的时候注意不要紧贴图片边缘
  
我有点抓狂了，我一共跑了三个数据集，开始的是PascalVOC2007，没问题，第二个数据集出现了pdb问题，确实如你所说的Bbox紧贴边缘，没时间重新标注图片，还好在修改pascal_voc.py和imdb.py代码之后，运行成功。但是在跑第三个数据集的时候又出现了pdb问题，我自认为紧贴边缘的问题已经解决了，现在这个问题又出现了，请问你知道还有可能的原因吗？或者你还在其他数据集上试过吗？
 第二个问题就是，这份代码不能计算mAp，你知道怎么修改吗？
  
是训练一开始就出现pdb的问题还是训练了几次iteration后才出现这个问题

**Comment by XN-0808** [comment]
> > > > > I also met the question, because the picture is too big, originally, the size of my picture is about 980_1000, i resized it as 512_512, it's ok
> > > > 
> > > > 
> > > > This problem may be related to the size of the image, but my image size is normal, but the same problem occurs
> > > 
> > > 
> > > 是用的自己的数据集吗，可能是标注的问题，标注的时候注意不要紧贴图片边缘
> > 
> > 
> > 我有点抓狂了，我一共跑了三个数据集，开始的是PascalVOC2007，没问题，第二个数据集出现了pdb问题，确实如你所说的Bbox紧贴边缘，没时间重新标注图片，还好在修改pascal_voc.py和imdb.py代码之后，运行成功。但是在跑第三个数据集的时候又出现了pdb问题，我自认为紧贴边缘的问题已经解决了，现在这个问题又出现了，请问你知道还有可能的原因吗？或者你还在其他数据集上试过吗？
> > 第二个问题就是，这份代码不能计算mAp，你知道怎么修改吗？
> 
> 是训练一开始就出现pdb的问题还是训练了几次iteration后才出现这个问题

是在训练了几个iteration出现的问题

**Comment by lccate** [comment]
> 我是训练一会儿再出现的，我跑的是cityperson数据集，你跑的是这个数据吗
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "ccate"<notifications@github.com>; 发送时间: 2018年12月10日(星期一) 下午5:26 收件人: "dBeker/Faster-RCNN-TensorFlow-Python3.5"<Faster-RCNN-TensorFlow-Python3.5@noreply.github.com>; 抄送: "唯y1╮拥有"<1214158021@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [dBeker/Faster-RCNN-TensorFlow-Python3.5] I met a strangequstion,and don't know how to fix it,I hope to get your help,Thanks (#29) I also met the question, because the picture is too big, originally, the size of my picture is about 980_1000, i resized it as 512_512, it's ok This problem may be related to the size of the image, but my image size is normal, but the same problem occurs 是用的自己的数据集吗，可能是标注的问题，标注的时候注意不要紧贴图片边缘 我有点抓狂了，我一共跑了三个数据集，开始的是PascalVOC2007，没问题，第二个数据集出现了pdb问题，确实如你所说的Bbox紧贴边缘，没时间重新标注图片，还好在修改pascal_voc.py和imdb.py代码之后，运行成功。但是在跑第三个数据集的时候又出现了pdb问题，我自认为紧贴边缘的问题已经解决了，现在这个问题又出现了，请问你知道还有可能的原因吗？或者你还在其他数据集上试过吗？ 第二个问题就是，这份代码不能计算mAp，你知道怎么修改吗？ 是训练一开始就出现pdb的问题还是训练了几次iteration后才出现这个问题 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

把data/cache/里面的pkl文件删掉再重新跑一下试试

**Comment by lccate** [comment]
> > > > > > I also met the question, because the picture is too big, originally, the size of my picture is about 980_1000, i resized it as 512_512, it's ok
> > > > > 
> > > > > 
> > > > > This problem may be related to the size of the image, but my image size is normal, but the same problem occurs
> > > > 
> > > > 
> > > > 是用的自己的数据集吗，可能是标注的问题，标注的时候注意不要紧贴图片边缘
> > > 
> > > 
> > > 我有点抓狂了，我一共跑了三个数据集，开始的是PascalVOC2007，没问题，第二个数据集出现了pdb问题，确实如你所说的Bbox紧贴边缘，没时间重新标注图片，还好在修改pascal_voc.py和imdb.py代码之后，运行成功。但是在跑第三个数据集的时候又出现了pdb问题，我自认为紧贴边缘的问题已经解决了，现在这个问题又出现了，请问你知道还有可能的原因吗？或者你还在其他数据集上试过吗？
> > > 第二个问题就是，这份代码不能计算mAp，你知道怎么修改吗？
> > 
> > 
> > 是训练一开始就出现pdb的问题还是训练了几次iteration后才出现这个问题
> 
> 是在训练了几个iteration出现的问题

把data/cache/里面的pkl文件删掉再重新跑一下试试

**Comment by niuniu111** [comment]
这些都试过了，不行呢




------------------ 原始邮件 ------------------
发件人: "ccate"<notifications@github.com>;
发送时间: 2018年12月10日(星期一) 下午5:44
收件人: "dBeker/Faster-RCNN-TensorFlow-Python3.5"<Faster-RCNN-TensorFlow-Python3.5@noreply.github.com>;
抄送: "唯y1╮拥有"<1214158021@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [dBeker/Faster-RCNN-TensorFlow-Python3.5] I met a strangequstion,and don't know how to fix it,I hope to get your help,Thanks (#29)



      
I also met the question, because the picture is too big, originally, the size of my picture is about 980_1000, i resized it as 512_512, it's ok
  
This problem may be related to the size of the image, but my image size is normal, but the same problem occurs
  
是用的自己的数据集吗，可能是标注的问题，标注的时候注意不要紧贴图片边缘
  
我有点抓狂了，我一共跑了三个数据集，开始的是PascalVOC2007，没问题，第二个数据集出现了pdb问题，确实如你所说的Bbox紧贴边缘，没时间重新标注图片，还好在修改pascal_voc.py和imdb.py代码之后，运行成功。但是在跑第三个数据集的时候又出现了pdb问题，我自认为紧贴边缘的问题已经解决了，现在这个问题又出现了，请问你知道还有可能的原因吗？或者你还在其他数据集上试过吗？
 第二个问题就是，这份代码不能计算mAp，你知道怎么修改吗？
  
是训练一开始就出现pdb的问题还是训练了几次iteration后才出现这个问题
  
是在训练了几个iteration出现的问题
  
把data/cache/里面的pkl文件删掉再重新跑一下试试

**Comment by XN-0808** [comment]
> > > > > > > I also met the question, because the picture is too big, originally, the size of my picture is about 980_1000, i resized it as 512_512, it's ok
> > > > > > 
> > > > > > 
> > > > > > This problem may be related to the size of the image, but my image size is normal, but the same problem occurs
> > > > > 
> > > > > 
> > > > > 是用的自己的数据集吗，可能是标注的问题，标注的时候注意不要紧贴图片边缘
> > > > 
> > > > 
> > > > 我有点抓狂了，我一共跑了三个数据集，开始的是PascalVOC2007，没问题，第二个数据集出现了pdb问题，确实如你所说的Bbox紧贴边缘，没时间重新标注图片，还好在修改pascal_voc.py和imdb.py代码之后，运行成功。但是在跑第三个数据集的时候又出现了pdb问题，我自认为紧贴边缘的问题已经解决了，现在这个问题又出现了，请问你知道还有可能的原因吗？或者你还在其他数据集上试过吗？
> > > > 第二个问题就是，这份代码不能计算mAp，你知道怎么修改吗？
> > > 
> > > 
> > > 是训练一开始就出现pdb的问题还是训练了几次iteration后才出现这个问题
> > 
> > 
> > 是在训练了几个iteration出现的问题
> 
> 把data/cache/里面的pkl文件删掉再重新跑一下试试

我试过了行不通，难道真的要resize再重新标注吗。。。。。。

**Comment by dBeker** [comment]
Use English in issues ffs!
