### ISSUE TITLE
cant  open ucrt.lib

### ISSUE THREAD

**Issue by TangtangQ** [dBeker/Faster-RCNN-TensorFlow-Python3#3]
When run    python setup.py build_ext --inplace    occurs  this error

**Comment by dBeker** [comment]
Couldn't reproduce it. Can you give more details?

**Comment by TangtangQ** [comment]
I  have already solved it

**Comment by dBeker** [comment]
Can you please push the changes to fix this issue please? So, everyone can get the solution.

**Comment by TangtangQ** [comment]
Add the file ‘Windows Kits\10\Lib\10.0.10586.0\ucrt’ to library directory
This issue is related to vs 2015 ，you should check the configuration about vs
