### ISSUE TITLE
AssertionError: Path does not exist

### ISSUE THREAD

**Issue by 759420184** [dBeker/Faster-RCNN-TensorFlow-Python3#30]
File "C:\Faster-RCNN-TensorFlow-Python3.5-master\lib\datasets\pascal_voc.py", line 84, in _load_image_set_index
    'Path does not exist: {}'.format(image_set_file)
AssertionError: Path does not exist: C:\Faster-RCNN-TensorFlow-Python3.5-master\data\VOCdevkit2007\VOC2007\ImageSets\Main\trainval.txt

**Comment by lccate** [comment]
the datest is wrong，try another voc dateset
