### ISSUE TITLE
OSError: output\vgg16\voc_2007_trainval+voc_2012_trainval\default\vgg16_faster_rcnn_iter_70000.ckpt.meta not found. Did you download the proper networks from our server and place them properly?

### ISSUE THREAD

**Issue by lccate** [dBeker/Faster-RCNN-TensorFlow-Python3#33]
I have already trained the train.py, when I open demo.py and run, the error occurs:
OSError: output\vgg16\voc_2007_trainval+voc_2012_trainval\default\vgg16_faster_rcnn_iter_70000.ckpt.meta not found.
Did you download the proper networks from our server and place them properly?
do you know that?

**Comment by MulinYu** [comment]
How do you solve this problem？pls tell me.

**Comment by lccate** [comment]
make a new file output\vgg16\voc_2007_trainval+voc_2012_trainval\default\ by yourself

**Comment by guanzy2012** [comment]
where did you make this new file? Pls tell me

**Comment by lccate** [comment]
> where did you make this new file? Pls tell me

make a new file output\vgg16\voc_2007_trainval+voc_2012_trainval\default\ by yourself

**Comment by guanzy2012** [comment]
I have place them properly. Thank you.
