### ISSUE TITLE
Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2 Traceback (most recent call last):   File "C:/Users/lcc/Desktop/Faster-RCNN-TensorFlow-Python3.5-master/demo2.py", line 141, in <module>     raise NotImplementedError NotImplementedError

### ISSUE THREAD

**Issue by lccate** [dBeker/Faster-RCNN-TensorFlow-Python3#35]
error ：
Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
Traceback (most recent call last):
  File "C:/Users/lcc/Desktop/Faster-RCNN-TensorFlow-Python3.5-master/demo2.py", line 141, in <module>
    raise NotImplementedError
NotImplementedError

**Comment by morpheusthewhite** [comment]
It is a warning about the fact that your CPU has additional features that the used TF was not compiled to use; it will work, but slower than it could
