### ISSUE TITLE
Should I run the file “fetch_faster_rcnn_models.sh”？

### ISSUE THREAD

**Issue by EdwardVincentMa** [dBeker/Faster-RCNN-TensorFlow-Python3#43]
I can not run this file and can not  get the “voc_0712_80k-110k.tgz”.  Because The URL is wrong.

**Comment by morpheusthewhite** [comment]
You don't need to run that.

 You can find dataset [here](https://github.com/rbgirshick/py-faster-rcnn#beyond-the-demo-installation-for-training-and-testing-models) and neural nets [here](http://download.tensorflow.org/models/vgg_16_2016_08_28.tar.gz)
