### ISSUE TITLE
what's the use of step 4?

### ISSUE THREAD

**Issue by lccate** [dBeker/Faster-RCNN-TensorFlow-Python3#46]
4- Go to ./data/coco/PythonAPI

      Run python setup.py build_ext --inplace

      Run python setup.py build_ext install

**Comment by morpheusthewhite** [comment]
It is needed to compile some python files

**Comment by GUUUUG** [comment]
> 4-转到./data/coco/PythonAPI
> 
> ```
>   Run python setup.py build_ext --inplace
> 
>   Run python setup.py build_ext install
> ```

error: Unable to find vcvarsall.bat
how to solve

**Comment by morpheusthewhite** [comment]
https://github.com/dBeker/Faster-RCNN-TensorFlow-Python3/issues/76 just look at the provious issues
