### ISSUE TITLE
when i run demo.py the error occurs

### ISSUE THREAD

**Issue by nic03** [dBeker/Faster-RCNN-TensorFlow-Python3#49]

**Comment by nic03** [comment]
when i was running my  own dataset,there is a issue exist as follow:>Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint.

**Comment by Monti03** [comment]
How did you solve this error?
