### ISSUE TITLE
can't open https://github.com/tensorflow/models/tree/master/slim#pre-trained-models

### ISSUE THREAD

**Issue by ZJL717** [dBeker/Faster-RCNN-TensorFlow-Python3#5]
[https://github.com/tensorflow/models/tree/master/slim#pre-trained-models](url)
it shows 404

**Comment by dBeker** [comment]
Tensorflow has updated the repo structure. 
Please use https://github.com/tensorflow/models/tree/master/research/slim#pre-trained-models 
I will update the links
