### ISSUE TITLE
我win10+python3.66+vs2017+cuda9.2下运行tensorflow版的faster-Rcnn    配置Faster-RCNN（网上找的的都是基于python3.5的，不支持py3.6，本文主要尝试用py3.6配置） https://blog.csdn.net/qq_41895190/article/details/82877883

### ISSUE THREAD

**Issue by QQ2737499951** [dBeker/Faster-RCNN-TensorFlow-Python3#51]
我win10+python3.66+vs2017+cuda9.2下运行tensorflow版的faster-Rcnn
 

配置Faster-RCNN（网上找的的都是基于python3.5的，不支持py3.6，本文主要尝试用py3.6配置）
https://blog.csdn.net/qq_41895190/article/details/82877883

**Comment by lccate** [comment]
> 我win10+python3.66+vs2017+cuda9.2下运行tensorflow版的faster-Rcnn
> 
> 配置Faster-RCNN（网上找的的都是基于python3.5的，不支持py3.6，本文主要尝试用py3.6配置）
> https://blog.csdn.net/qq_41895190/article/details/82877883

你好，看了你的博客，请问最后demo运行后的图片，train后面的0.595是表示什么，准确率吗？

**Comment by i4yyds** [comment]
中国人支持一下！
