### ISSUE TITLE
1

### ISSUE THREAD

**Issue by zb521** [dBeker/Faster-RCNN-TensorFlow-Python3#53]
MAP 值呢

**Comment by lccate** [comment]
what‘s the meaning of the demo.py result: car 0.897?

**Comment by zb521** [comment]
yes，NO car 0.897






------------------ 原始邮件 ------------------
发件人: "ccate"<notifications@github.com>;
发送时间: 2018年12月1日(星期六) 晚上6:41
收件人: "dBeker/Faster-RCNN-TensorFlow-Python3.5"<Faster-RCNN-TensorFlow-Python3.5@noreply.github.com>;
抄送: "爱之破"<864196669@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [dBeker/Faster-RCNN-TensorFlow-Python3.5] 1 (#53)




what‘s the meaning of the demo.py result: car 0.897?

**Comment by lccate** [comment]
> yes，NO car 0.897
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "ccate"<notifications@github.com>; 发送时间: 2018年12月1日(星期六) 晚上6:41 收件人: "dBeker/Faster-RCNN-TensorFlow-Python3.5"<Faster-RCNN-TensorFlow-Python3.5@noreply.github.com>; 抄送: "爱之破"<864196669@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [dBeker/Faster-RCNN-TensorFlow-Python3.5] 1 (#53) what‘s the meaning of the demo.py result: car 0.897? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

你好，你的意思是map值就是图片上的那个0.897吗

**Comment by zb521** [comment]
不是的；那个会显示出来20类物体的AP值，图片上的只是针对这张图片

**Comment by lccate** [comment]
> 不是的；那个会显示出来20类物体的AP值，图片上的只是针对这张图片

请问针对这张图片的ap值是怎么算出来的呢

**Comment by niuniu111** [comment]
ap值是运行完demo自己计算的吗

**Comment by morpheusthewhite** [comment]
You should speak English for the sake of the others
