### ISSUE TITLE
mAP

### ISSUE THREAD

**Issue by XN-0808** [dBeker/Faster-RCNN-TensorFlow-Python3#54]
I noticed that the projet didn't plot the mAP ,how can i revise the code?

**Comment by GZYZG** [comment]
Can you tell me how to solve this problem?Thank you!

**Comment by XN-0808** [comment]
> Can you tell me how to solve this problem?Thank you!
给你个CSDN博客链接：
https://blog.csdn.net/beyond_xnsx/article/details/79910900

**Comment by morpheusthewhite** [comment]
I added it here https://github.com/morpheusthewhite/Faster-RCNN-TensorFlow-Python3.5/commit/8c5307c4c92916e12fef436b19872eec7bede030 in my fork
