### ISSUE TITLE
What do the Numbers after the test results mean？precision

### ISSUE THREAD

**Issue by lccate** [dBeker/Faster-RCNN-TensorFlow-Python3#55]

**Comment by lccate** [comment]
for example ，i input a picture and output "car 0.997",what do the 0.997 mean?

**Comment by gwspotex** [comment]
that's mean the Probability

**Comment by morpheusthewhite** [comment]
It is score that tells you how much good is your network in classifying the given images

You can find more [here](https://developers.google.com/machine-learning/crash-course/classification/precision-and-recall)
