### ISSUE TITLE
there is a problem about convergence

### ISSUE THREAD

**Issue by guokainew** [dBeker/Faster-RCNN-TensorFlow-Python3#58]
When i train my image use this Code,there is a problem about convergence: Training results shows that the 'total loss' is fluctuate around 2 ,and did not decrease anymore; Second, the 'loss_box' always decay to zero and it will rise a little only; Third, the training is always cut off, no reason; Fourth, the candidate boxes are generally small than the fact; Fiveth, when i run the demo there are undetectable object. So, what happen to my project,  please reply to me as soon as possible,thank U!

**Comment by morpheusthewhite** [comment]
1. I have enough information to help you, did you use this repository without changing anything?
2. Same as 1
3. What do you mean? Doesn't train start?
4. That depends on the annotations you are using 
5. The demo detects only one object per image

**Comment by guokainew** [comment]
I am very pleasure to receive the reply from you, and i have solved this problem by some adjustment, thank yoo very much!


 
---Original---

**Comment by morpheusthewhite** [comment]
You're welcome

**Comment by AICVHub** [comment]
> I am very pleasure to receive the reply from you, and i have solved this problem by some adjustment, thank yoo very much!
> […](#)
> ---Original--- From: "morpheusthewhite"<notifications@github.com> Date: Thu, May 23, 2019 17:32 PM To: "dBeker/Faster-RCNN-TensorFlow-Python3.5"<Faster-RCNN-TensorFlow-Python3.5@noreply.github.com>; Cc: "guokainew"<2496296333@qq.com>;"Author"<author@noreply.github.com>; Subject: Re: [dBeker/Faster-RCNN-TensorFlow-Python3.5] there is a problem about convergence (#58) I have enough information to help you, did you use this repository without changing anything? Same as 1 What do you mean? Doesn't train start? That depends on the annotations you are using The demo detects only one object per image — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

I meet the same problems! Glad to see you issue.
How did you do to slove this problem? Could you teach me about it?
