### ISSUE TITLE
how to accelerate the speed of dectecting?

### ISSUE THREAD

**Issue by GZYZG** [dBeker/Faster-RCNN-TensorFlow-Python3#61]
I train my own dataset with faster-rcnn, and there is only on class,but it cost 8 to 9 seconds on every image.That's too slow for me project.Is this because that I use cpu to train? Can anyone help me ?Thank you very much.

**Comment by morpheusthewhite** [comment]
Yes, of course using CPU instead of GPU slows you down

If you are worried about the fact the it is a lot, it is normal, the process is really intensive
