### ISSUE TITLE
How to change the size of anchor?

### ISSUE THREAD

**Issue by Carp-love** [dBeker/Faster-RCNN-TensorFlow-Python3#66]
Hello, could you please tell me how to change the size of anchor? And how to call the generate_anchor function? I can't find any place in this code where the function be called. Thank you.

**Comment by morpheusthewhite** [comment]
It is used in `lib/layer_utils/snippets.py` (line 18) and in `lib/layer_utils/generate_anchors.py` (line 112)

**Comment by Carp-love** [comment]
okkay, thank you

**Comment by xiezequn123** [comment]
https://github.com/dBeker/Faster-RCNN-TensorFlow-Python3/issues/66#issuecomment-487830813
Hello, how can I change the number of anchors? I set scales to [4,8,16,32], and what other files need to be modified?thanks you

**Comment by xiezequn123** [comment]
> 它用于`lib/layer_utils/snippets.py`（第18行）和`lib/layer_utils/generate_anchors.py`（第112行）

Hello, how can I change the number of anchors? I set scales to [4,8,16,32], and what other files need to be modified?thanks you
