### ISSUE TITLE
Abnormal stop

### ISSUE THREAD

**Issue by imglearning** [dBeker/Faster-RCNN-TensorFlow-Python3#67]
![图片](https://user-images.githubusercontent.com/44295376/56630901-ae273780-6685-11e9-88d3-49257b686cc7.png)

**Comment by morpheusthewhite** [comment]
Pull the recent commits (it was fixed with https://github.com/dBeker/Faster-RCNN-TensorFlow-Python3.5/commit/6462763db550994ca6e0955cf3233173d905855e)

**Comment by dBeker** [comment]
@morpheusthewhite Thanks for the PR. Merged to master

**Comment by imglearning** [comment]
Thank You ，Ｉ have solved the problem
