### ISSUE TITLE
Could you please tell me how to get the mAP? 

### ISSUE THREAD

**Issue by AriadneZhao** [dBeker/Faster-RCNN-TensorFlow-Python3#68]
I have trained on my own DS. But I have no idea how to get the map. Someone plz help me!!!!!!

**Comment by morpheusthewhite** [comment]
https://medium.com/@jonathan_hui/map-mean-average-precision-for-object-detection-45c121a31173

**Comment by AriadneZhao** [comment]
> https://medium.com/@jonathan_hui/map-mean-average-precision-for-object-detection-45c121a31173

I read your fork in morpheusthewhite@8c5307c before and cloned it. But I noticed that there are two documents named Annotation_imagenet and Annotation in C:\Faster-RCNN-TensorFlow-Python3.5\data\imagenet and I don't know which should I add my xml documents in. 

Plz help me about that thx!!!

**Comment by AriadneZhao** [comment]
> https://medium.com/@jonathan_hui/map-mean-average-precision-for-object-detection-45c121a31173

I read your fork in morpheusthewhite/Faster-RCNN-TensorFlow-Python3.5@8c5307c before and cloned it. But I noticed that there are two documents named Annotation_imagenet and Annotation in C:\Faster-RCNN-TensorFlow-Python3.5\data\imagenet and I don't know which should I add my xml documents in.
Plz help me about that thx!!!

**Comment by morpheusthewhite** [comment]
You should put them in `data/imagenet/Annotation_imagenet` (I'll soon update the README)

**Comment by MsRabbits** [comment]
> https://medium.com/@jonathan_hui/map-mean-average-precision-for-object-detection-45c121a31173
this address is invaid, can you give another one? Thx

**Comment by morpheusthewhite** [comment]
> > https://medium.com/@jonathan_hui/map-mean-average-precision-for-object-detection-45c121a31173
> > this address is invaid, can you give another one? Thx

It works for me
