### ISSUE TITLE
Can python3.6 use this project?

### ISSUE THREAD

**Issue by YuanYunjing** [dBeker/Faster-RCNN-TensorFlow-Python3#69]

**Comment by morpheusthewhite** [comment]
No, you need python 3.5 (I experienced a lot of problems and crashes when launching it with python 3.6)

**Comment by dBeker** [comment]
If you can fix it for python 3.6, please create a PR.

**Comment by morpheusthewhite** [comment]
I recently tested python3.6 and python 3.7 and both worked (I also updated README) so you can use them without problems
