### ISSUE TITLE
error: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by LouChengLin** [dBeker/Faster-RCNN-TensorFlow-Python3#7]
i don't know what file does the system want to find

D:\Faster-RCNN-TensorFlow-Python3.5-master\data\coco\PythonAPI>python setup.py build_ext install
running build_ext
error: [WinError 2] 系统找不到指定的文件。
D:\Faster-RCNN-TensorFlow-Python3.5-master\data\coco\PythonAPI>python setup.py build_ext --inplace
running build_ext
error: [WinError 2] 系统找不到指定的文件。

"系统找不到指定的文件" means "The system cannot find the specified file"

**Comment by dBeker** [comment]
I don't know which file you cannot find. Please debug.

**Comment by wxd0301** [comment]
楼主怎么解决了

**Comment by sdzbft** [comment]
> 楼主怎么解决了

请问这个问题你们解决了吗，我也是这问题

**Comment by sdzbft** [comment]
> running build_ext
> error: [WinError 2] 系统找不到指定

我也是这个问题，请问这个如何解决的呀，，谢谢
