### ISSUE TITLE
How to view the loss curve in the tensorboard?

### ISSUE THREAD

**Issue by mayflyfy** [dBeker/Faster-RCNN-TensorFlow-Python3#74]
How to change the code to view the loss curve in the tensorboard.
I see that other versions of Faster-rcnn have logs in the directory “experiments/logs/xxx”  ， but this versions does not have it.

i would appreciate it if you answer my question.

**Comment by morpheusthewhite** [comment]
This project does not log on Tensorboard by default, so you'll not find that folder; you can easily add it as done [here](https://github.com/morpheusthewhite/Faster-RCNN-TensorFlow-Python3.5/commit/8c5307c4c92916e12fef436b19872eec7bede030)

**Comment by mayflyfy** [comment]
> This project does not log on Tensorboard by default, so you'll not find that folder; you can easily add it as done [here](https://github.com/morpheusthewhite/Faster-RCNN-TensorFlow-Python3.5/commit/8c5307c4c92916e12fef436b19872eec7bede030)

thank you！

**Comment by morpheusthewhite** [comment]
You're welcome
