### ISSUE TITLE
building 'pycocotools._mask' extension error: Unable to find vcvarsall.bat

### ISSUE THREAD

**Issue by qianbeidexiaoyu** [dBeker/Faster-RCNN-TensorFlow-Python3#76]
reference: 
http://www.aobosir.com/blog/2016/11/26/Python-pip-error-Unable-to-find-vcvarsall-bat/

**Comment by morpheusthewhite** [comment]
You should install Visual Studio with Python build support

Source: https://devblogs.microsoft.com/python/unable-to-find-vcvarsall-bat/

> For Python 3.5 and later, installing Visual Studio 2015 is sufficient and you can now try to pip install the package again.
> Install Visual Studio 2017, select the Python development workload and the Native development tools option.

**Comment by wjwABCDEFG** [comment]
If you use jupyter, you can install vc and vs2015_runtime in navigator. Or you can install visual studio
