### ISSUE TITLE
How to replace VGG with resnet

### ISSUE THREAD

**Issue by S0soo** [dBeker/Faster-RCNN-TensorFlow-Python3#79]
I tried to modify the training file, but there were still many mistakes. Did anyone succeed

**Comment by morpheusthewhite** [comment]
I need more information to help you.

What's the error printed in the console?

**Comment by S0soo** [comment]
> I need more information to help you.
> 
> What's the error printed in the console?

File "E:\faster-rcnn\lib\nets\resnet_v1.py", line 27, in <module>
  weight_decay=cfg.TRAIN.WEIGHT_DECAY,
AttributeError: module 'lib.config.config' has no attribute 'TRAIN'
II don't know how to deal with this error, 
if you know, please help me,
 thanks a lot

**Comment by morpheusthewhite** [comment]
Try to replace the following line (27)
```python
                     weight_decay=cfg.TRAIN.WEIGHT_DECAY,
```

with 

```python
                     weight_decay=cfg.FLAGS.weight_decay,
```

**Comment by morpheusthewhite** [comment]
After some tests I found out that `resnet` needs some effort to work, now it's not supported.

You can either create a pull request or wait for @dBeker's answer

**Comment by S0soo** [comment]
Thank you very much, I understand, and I find cfg.resnet and cfg.pooling_size to be unmanageable

**Comment by S0soo** [comment]
https://github.com/endernewton/tf-faster-rcnn
I have successfully trained according to this, and I will have a test after the training. Thank you very much for your advice

**Comment by morpheusthewhite** [comment]
You're welcome

**Comment by chenjjjjuu** [comment]
> https://github.com/endernewton/tf-faster-rcnn
> I have successfully trained according to this, and I will have a test after the training. Thank you very much for your advice

hi !Can you used resnet to trained your data on fasterrcnn by this link?I have been to try it but faild!

**Comment by S0soo** [comment]
yes，you can download files that need to be replaced in my GitHub

**Comment by chenjjjjuu** [comment]
> yes，you can download files that need to be replaced in my GitHub

ok,I'll try it. thanks

**Comment by S0soo** [comment]
> > yes，you can download files that need to be replaced in my GitHub
> 
> ok,I'll try it. thanks

You're welcome. I wish you success.

**Comment by chenjjjjuu** [comment]
> > > yes，you can download files that need to be replaced in my GitHub
> > 
> > 
> > ok,I'll try it. thanks
> 
> You're welcome. I wish 


> > > yes，you can download files that need to be replaced in my GitHub
> > 
> > 
> > ok,I'll try it. thanks
> 
> You're welcome. I wish you success.

excuse me. I try your script in linux not windows.there have an error in datasets/pascal_voc.py in  line 34,what's the mean of "self.path = r'E:\faster-rcnn\labels_10_JYsf.txt'",and where is my labels_10_JYsf.txt?

**Comment by S0soo** [comment]
This is your class name, a .txt file

**Comment by chenjjjjuu** [comment]
> This is your class name, a .txt file

can you show me your .txt for example please? I don't konw which form should the .txt be.  I just have one class named flower.

**Comment by S0soo** [comment]
like this
![image](https://user-images.githubusercontent.com/38646375/65855978-ffed8f80-e392-11e9-8d02-eb1f26a9c401.png)

**Comment by chenjjjjuu** [comment]
and where can download resnet_v1_50.cpkg?

**Comment by S0soo** [comment]
![image](https://user-images.githubusercontent.com/38646375/65856541-822a8380-e394-11e9-9e95-df58dfb77952.png)

**Comment by chenjjjjuu** [comment]
> ![image](https://user-images.githubusercontent.com/38646375/65856541-822a8380-e394-11e9-9e95-df58dfb77952.png)

i find it. thanks

**Comment by chenjjjjuu** [comment]
> ![image](https://user-images.githubusercontent.com/38646375/65856541-822a8380-e394-11e9-9e95-df58dfb77952.png)


> ![image](https://user-images.githubusercontent.com/38646375/65856541-822a8380-e394-11e9-9e95-df58dfb77952.pdatang)

like this

> like this
> ![image](https://user-images.githubusercontent.com/38646375/65855978-ffed8f80-e392-11e9-8d02-eb1f26a9c401.png)

datasets like this?
VOCdevkit2007
-VOC2007
-Annotations  Imagesets JEPGImages

**Comment by S0soo** [comment]
yes，

**Comment by chenjjjjuu** [comment]
hello ! 
Do you know how to deal with this error? (I've been do all  as your step and ).


Traceback (most recent call last):
  File "train-resnet.py", line 223, in <module>
    train.train()
  File "train-resnet.py", line 154, in train
    blobs = self.data_layer.forward()
  File "/home/chen/chen/faser-resnet/lib/layer_utils/roi_data_layer.py", line 75, in forward
    blobs = self._get_next_minibatch()
  File "/home/chen/chen/faser-resnet/lib/layer_utils/roi_data_layer.py", line 71, in _get_next_minibatch
    return get_minibatch(minibatch_db, self._num_classes)
  File "/home/chen/chen/faser-resnet/lib/utils/minibatch.py", line 29, in get_minibatch
    assert (cfg.FLAGS.batch_size % num_images == 0), 'num_images ({}) must divide BATCH_SIZE ({})'.format(num_images, cfg.FLAGS.batch_size)
ZeroDivisionError: integer division or modulo by zero

**Comment by chenjjjjuu** [comment]
> https://github.com/endernewton/tf-faster-rcnn
> I have successfully trained according to this, and I will have a test after the training. Thank you very much for your advice

could you send me your file plesae, I can't run this in resnet finally.

**Comment by S0soo** [comment]
> > https://github.com/endernewton/tf-faster-rcnn
> > I have successfully trained according to this, and I will have a test after the training. Thank you very much for your advice
> 
> could you send me your file plesae, I can't run this in resnet finally.

I'm sorry, I can't send you the code I used, because I added a lot of content on this basis, the modified code is very different from the previous one. But I can try to help you solve some problems.

**Comment by chenjjjjuu** [comment]
thank you so much and what's your mean 'cfg.resnet and cfg.pooling_size to be unmanageable'.

(https://github.com/S0soo/tf-faster-rcnn-resnet)This code can run in linux?

**Comment by S0soo** [comment]
This runs in win. To run in linux, use https://github.com/endernewton/tf-faster-rcnn

**Comment by chenjjjjuu** [comment]
ok  I'll try ------------------ 原始邮件 ------------------
发件人: "YLF"<notifications@github.com>
发送时间: 2019年10月4日(星期五) 下午5:37
收件人: "dBeker/Faster-RCNN-TensorFlow-Python3"<Faster-RCNN-TensorFlow-Python3@noreply.github.com>;
抄送: "chenjjjjuu"<1540358700@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [dBeker/Faster-RCNN-TensorFlow-Python3] How to replace VGG withresnet (#79)



This runs in win. To run in linux, use https://github.com/endernewton/tf-faster-rcnn
 
&mdash;

**Comment by S0soo** [comment]
'cfg.resnet and cfg.pooling_size to be unmanageable' means if you want to use resnet, you need to add some extra hyperparameters

**Comment by S0soo** [comment]
For this demo, if you have any questions, you can add my QQ, 1572128279.
