### ISSUE TITLE
TypeError when launching train.py

### ISSUE THREAD

**Issue by YYJ27** [dBeker/Faster-RCNN-TensorFlow-Python3#80]
File "D:\Faster-RCNN-TensorFlow-Python3-master\lib\nets\vgg16.py", line 66, in get_variables_to_restore
    if v.name.split(':')[0] in var_keep_dic:
TypeError: argument of type 'NoneType' is not iterable

**Comment by YYJ27** [comment]
I have solved this problem and modified vgg_16.ckt to vgg16.ckt

**Comment by RongMiao** [comment]
> I have solved this problem and modified vgg_16.ckt to vgg16.ckt

i have made the same mistake. thanks
