### ISSUE TITLE
I want to compiled cython modules with sm75 architecture (RTX2080TI)

### ISSUE THREAD

**Issue by gwspotex** [dBeker/Faster-RCNN-TensorFlow-Python3#81]
Can you teach me how to change architecture?
![image](https://user-images.githubusercontent.com/32533059/60729881-57d45000-9f76-11e9-82d0-a1c77985f6d7.png)

**Comment by morpheusthewhite** [comment]
You just need to follow instructions in the numbered list (install tensorflow-gpu)

**Comment by gwspotex** [comment]
sorry, but where is the numbered list? instructions?

**Comment by gwspotex** [comment]
there are question&answer: https://github.com/endernewton/tf-faster-rcnn/issues/5
it seems the dismatch architecture makes the result get some loss，i don't how complie the sm61(gtx 1080ti)->sm75(rtx2080ti)

**Comment by morpheusthewhite** [comment]
In the [README](https://github.com/dBeker/Faster-RCNN-TensorFlow-Python3/blob/master/README.md)

**Comment by morpheusthewhite** [comment]
> there are question&answer: [endernewton/tf-faster-rcnn#5](https://github.com/endernewton/tf-faster-rcnn/issues/5)
> it seems the dismatch architecture makes the result get some loss，i don't how complie the sm61(gtx 1080ti)->sm75(rtx2080ti)

That's another project, contact its mantainer

**Comment by gwspotex** [comment]
ok :)，because i see the readme say there sm61 architecture and i just want using sm75 to change 
![image](https://user-images.githubusercontent.com/32533059/60733693-32e4da80-9f80-11e9-90e9-91966d842d72.png)

**Comment by morpheusthewhite** [comment]
I'll Update the README to clarify

**Comment by morpheusthewhite** [comment]
You are looking at some commit while you should read directly from the [README](https://github.com/dBeker/Faster-RCNN-TensorFlow-Python3/blob/master/README.md)
