### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by movie3105** [dBeker/Faster-RCNN-TensorFlow-Python3#84]
#i'm sorry if you think this question is stupid, but can since this using tensorflow can we convert this code to tflite and run it on android ?

**Comment by morpheusthewhite** [comment]
I think you don't need anything to run it on android, just download [termux](https://play.google.com/store/apps/details?id=com.termux&hl=en_US) and set up the project from command line (install python, needed dependencies etc.)

**Comment by movie3105** [comment]
do you have any tutorial about that @morpheusthewhite i'll really appreciate that.

**Comment by morpheusthewhite** [comment]
https://wiki.termux.com/wiki/Instructions_for_installing_python_packages

**Comment by movie3105** [comment]
but do we need to train the image again on android ? if yes doesn't it take long time to train it ?

**Comment by morpheusthewhite** [comment]
You can pass the saved checkpoint and use it for the demo
