### ISSUE TITLE
How to evaluate the model

### ISSUE THREAD

**Issue by wangken1994** [dBeker/Faster-RCNN-TensorFlow-Python3#86]
Hey, @dBeker 
Thanks for your excellent codes which can easily be run in Windows system.  After the train stage, I found there was no test file in your codes, that's I can't get the mAP to evaluate the train model. So, could you tell me how to get the mAP of the train midel or could you kindly publish the test file？

Best, 
Ken

**Comment by morpheusthewhite** [comment]
Look in the previous issues, the question has already been answered:

https://github.com/dBeker/Faster-RCNN-TensorFlow-Python3/issues/68 about getting the mAP

https://github.com/dBeker/Faster-RCNN-TensorFlow-Python3/issues/74 to enable tensorboard to visualize scores

To test the model on images run `demo.py`
