### ISSUE TITLE
Running train.py gives no output

### ISSUE THREAD

**Issue by grignarder** [dBeker/Faster-RCNN-TensorFlow-Python3#88]
I can't find any output weights file after i run train.py. Should I add some parameters when python train.py or just use `python train.py`?

Since no output is given, I met problems when trying to run demo.py.
Thanks a lot!

**Comment by morpheusthewhite** [comment]
No extra parameter is needed when running `python train.py`.

What problems do you meet when running `demo.py`?

**Comment by grignarder** [comment]
(tensorflow) C:\Faster-RCNN-TensorFlow-Python3>python demo.py
output\res101\voc_2007_trainval+voc_2012_trainval\default\res101_faster_rcnn_iter_110000.ckpt
Traceback (most recent call last):
  File "demo.py", line 123, in <module>
    'our server and place them properly?').format(tfmodel + '.meta'))
OSError: output\res101\voc_2007_trainval+voc_2012_trainval\default\res101_faster_rcnn_iter_110000.ckpt.meta not found.
Did you download the proper networks from our server and place them properly?

The output is like this. Is there anything that should be changed in the demo.py?
Sorry to trouble you.

**Comment by grignarder** [comment]
By the way, i modified the maximum iteration time to 100. I don't think it contributes to this problem.

**Comment by morpheusthewhite** [comment]
Yes, the checkpoint is saved every 5000 iterations, so if you reduce the iterations to 100 no checkpoint will be saved.

You can change the number of iterations necessary to save the checkpoint in `lib/config/config.py` (the variable is defined at line 44)
