### ISSUE TITLE
Code understanding

### ISSUE THREAD

**Issue by niuniu111** [dBeker/Faster-RCNN-TensorFlow-Python3#9]
Hello, I have read the code more deeply than it does, so I want to visualize it. The code seems to have the name of each layer and node, but nothing in the tensorboard, I looked at the output, he just output model, there is no log file, should I call the function inside to visualize?Can you give me some advice?Thanks

**Comment by dBeker** [comment]
You need to add summaries before training and use those summaries to training array like following: 

>   summary_writer= tf.summary.FileWriter("Path To Log file", graph=sess.graph)
>   summaries = set()
>   summaries.add(tf.summary.scalar("Loss1", loss1, family="Loss"))        
>   summaries.add(tf.summary.scalar("Loss2", loss2, family="Loss"))
>   summary_op = tf.summary.merge(list(summaries), name='summary_op')
>   sess.run([optimizer, loss, summary_op], feed_dict={"your feed dict"})

And then you can visualize everything through tensorboard.
Please check stackoverflow and tensorflow web site for summary usage

**Comment by niuniu111** [comment]
I first visualized loss_cls, loss_box, and when I used the advice you gave me to change the path and name to run, there was such a mistake: TypeError: scalar () got an unexpected keyword argument'family', here's the family also need to change? Your guidance is also needed

**Comment by niuniu111** [comment]
Hello, teacher, last time according to your suggestion, I wrote the code, there are such problems, TypeError: scalar () got an unexpected keyword argument'family', here's family also need to modify it? In addition, I see in network.py that there is such a statement self._summary_op = tf.summary.merge_all (), which conflicts with what I'm going to write?Hope for your guidance。Thanks!
