### ISSUE TITLE
AttributeError: module 'PIL' has no attribute 'Image'

### ISSUE THREAD

**Issue by morpheusthewhite** [dBeker/Faster-RCNN-TensorFlow-Python3#90]
`AttributeError: module 'PIL' has no attribute 'Image'`

_Originally posted by @movie3105 in https://github.com/dBeker/Faster-RCNN-TensorFlow-Python3/issues/87#issuecomment-519037997_

**Comment by morpheusthewhite** [comment]
Make sure you are using a supported version of Python (post here your python version (`python --version`))

You can try to reinstall pillow by
```bash
pip uninstall pillow
pip install pillow
```

**Comment by movie3105** [comment]
yup thank you it solve the problem
