### ISSUE TITLE
Trained model isn't saved: Tensorflow internal error

### ISSUE THREAD

**Issue by movie3105** [dBeker/Faster-RCNN-TensorFlow-Python3#92]
i finish training data but this error occured and the trained data didn't get save this the error snapshot:
![image](https://user-images.githubusercontent.com/52781140/62823436-e746d180-bbba-11e9-83e6-9b5ef94e6cc8.png)

how can i solve this ?

**Comment by morpheusthewhite** [comment]
Stop posting screen.

To help you I need the entire error traceback, please post it here

**Comment by movie3105** [comment]
so after a while i just realized that's just a exhausted memory after i see several post i realize that my ram can't take the training process so i upgrade my ram and this problem is solved,thank you
