### ISSUE TITLE
There is no output model after the training

### ISSUE THREAD

**Issue by Jai-wei** [dBeker/Faster-RCNN-TensorFlow-Python3#98]
There is no output model after the training，The final result is as follows（train.py)：

speed: 14.338s / iter
iter: 3991 / 4000, total loss: 0.024490
 >>> rpn_loss_cls: 0.001267
 >>> rpn_loss_box: 0.000509
 >>> loss_cls: 0.011721
 >>> loss_box: 0.010993

speed: 14.338s / iter
iter: 3992 / 4000, total loss: 0.048566
 >>> rpn_loss_cls: 0.001235
 >>> rpn_loss_box: 0.001046
 >>> loss_cls: 0.033571
 >>> loss_box: 0.012713

speed: 14.337s / iter
iter: 3993 / 4000, total loss: 0.053452
 >>> rpn_loss_cls: 0.001681
 >>> rpn_loss_box: 0.001608
 >>> loss_cls: 0.035508
 >>> loss_box: 0.014654

speed: 14.336s / iter
iter: 3994 / 4000, total loss: 0.070646
 >>> rpn_loss_cls: 0.000058
 >>> rpn_loss_box: 0.000423
 >>> loss_cls: 0.046126
 >>> loss_box: 0.024039

speed: 14.336s / iter
iter: 3995 / 4000, total loss: 0.036924
 >>> rpn_loss_cls: 0.000836
 >>> rpn_loss_box: 0.001194
 >>> loss_cls: 0.018513
 >>> loss_box: 0.016380

speed: 14.335s / iter
iter: 3996 / 4000, total loss: 0.085609
 >>> rpn_loss_cls: 0.001739
 >>> rpn_loss_box: 0.000387
 >>> loss_cls: 0.047054
 >>> loss_box: 0.036428

speed: 14.334s / iter
iter: 3997 / 4000, total loss: 0.029429
 >>> rpn_loss_cls: 0.000159
 >>> rpn_loss_box: 0.000223
 >>> loss_cls: 0.020920
 >>> loss_box: 0.008128

speed: 14.333s / iter
iter: 3998 / 4000, total loss: 0.053948
 >>> rpn_loss_cls: 0.002857
 >>> rpn_loss_box: 0.000448
 >>> loss_cls: 0.023264
 >>> loss_box: 0.027379

speed: 14.332s / iter
iter: 3999 / 4000, total loss: 0.079444
 >>> rpn_loss_cls: 0.000330
 >>> rpn_loss_box: 0.000551
 >>> loss_cls: 0.047870
 >>> loss_box: 0.030693

speed: 14.332s / iter
iter: 4000 / 4000, total loss: 0.123056
 >>> rpn_loss_cls: 0.002037
 >>> rpn_loss_box: 0.001161
 >>> loss_cls: 0.081516
 >>> loss_box: 0.038342

speed: 14.331s / iter
iter: 4001 / 4000, total loss: 0.073527
 >>> rpn_loss_cls: 0.000512
 >>> rpn_loss_box: 0.001229
 >>> loss_cls: 0.038448
 >>> loss_box: 0.033339

speed: 14.330s / iter

(py35-cpu) E:\Faster-RCNN-TensorFlow-Python3-2c52d601cae09fba0d9e445cd95d5af95d80d6c9>

**Comment by morpheusthewhite** [comment]
The output model is saved in `default` folder
